### ISSUE TITLE
Open external links in new browser window

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1604]
PR #1603 fixed a mistaken Markdown link introduced by me.

I noticed the PR creator uses a caret `^` behind the link.
This makes it so that the link is opened in a new browser window (`_blank`).

I think it makes sense to open external links (pages not part of book) in a new tab in the browser.
This way users don't accidentally navigate away from the book.

Quote from [Asciidoctor writers guide, links and images](https://asciidoctor.org/docs/asciidoc-writers-guide/#links-and-images):

> Since `_blank` is the most common window name, we’ve introduced shorthand for it. Just end the link text with a caret (`^`):

```
Let's view the raw HTML of the link:view-source:asciidoctor.org[Asciidoctor homepage^].
```

**Comment by HonkingGoose** [comment]
I can confirm that the caret `^` shorthand works properly when viewing the `progit.html` file. 🎉

I don't know if the caret works properly on the `git-scm.com` website, as they have not done their daily re-fresh run yet.

---

@ben Once I know for certain that the `^` caret also works properly on `git-scm.com` do you want a PR from me to make the change for all external links in the book?

**Comment by KZiemian** [comment]
Is this issue resolved by now?

**Comment by HonkingGoose** [comment]
No it's not resolved, because I only fixed one link. We're bound to have way more links that point to external resources (things that are not in the book).

For this issue to be resolved all external links should use the caret `^` shorthand.

**Comment by ben** [comment]
Wow, yeah, sorry for letting this one slip through. Absolutely, go right ahead.
